# ============================================================================
# local_runs.jl — local (non-cluster) job-script generator
# ============================================================================
#
# Exposes:  run_locally(commands_file, n_commands, codename; ...)
#
# Emits train_local_<ts>.sh or test_local_<ts>.sh — same contract as run_on_SLURM,
# but with no SLURM directives, no rsync staging, and runtime GPU detection.
#
# GPU detection at SCRIPT RUN time (not generation time), so the same script
# works whether you dispatch it on your Mac or a Linux workstation:
#
#   * Apple Silicon (Darwin arm64)   → USE_GPU=1, GPU_BACKEND=metal, 1 job total
#   * Linux with nvidia-smi present  → USE_GPU=1, GPU_BACKEND=cuda,
#                                       jobs = number of visible NVIDIA GPUs,
#                                       CUDA_VISIBLE_DEVICES set per parallel slot
#   * Anything else                  → USE_GPU=0, jobs = n_cpus (CPU fallback)
#
# Train mode always uses CPU (Enzyme's AD path can't run on GPU here), so GPU
# detection only runs in test mode.
#
# included by batch_run.jl.
# ============================================================================

using Dates

function run_locally(
    commands_file::String,
    n_commands::Int,
    codename::String;
    n_cpus::Int=4,
    working_dir::String=joinpath(@__DIR__, ".."),
    mode::Symbol=:train,
    n_gpus_per_node::Int=1,     # in test mode: cap on parallel GPU jobs even if more GPUs are present
    gpu_type::String="",        # informational only — actual backend is detected at runtime
)
    """
    Generate a local shell script that runs the commands in `commands_file`
    via GNU parallel. Prints the `bash <script>` invocation on completion.

    In test mode the generated script auto-detects Metal (Apple Silicon) or
    CUDA (Linux + nvidia-smi), falling back to CPU if neither is present.
    """
    if !(mode in (:train, :test))
        error("mode must be :train or :test, got :$(mode)")
    end

    is_test_mode = (mode == :test)
    timestamp = Dates.format(Dates.now(), "yyyy-mm-dd_HH-MM-SS")

    target_dir = joinpath(working_dir, codename)
    commands_dir = joinpath(target_dir, "cluster")
    logs_dir = joinpath(target_dir, "logs", "$(mode)_$(timestamp)")
    isdir(logs_dir) || mkpath(logs_dir)

    script_prefix = is_test_mode ? "test_local" : "train_local"
    script_file  = joinpath(commands_dir, "$(script_prefix)_$(timestamp).sh")

    # In train mode we run CPU-bound Julia processes in parallel — one thread each
    # so BLAS doesn't compete with GNU parallel over cores. In test mode we cap
    # parallel jobs at n_gpus_per_node so each Julia proc owns exactly one GPU
    # (real per-runtime GPU count is detected in the generated script itself).
    threads_per_job = is_test_mode ? max(1, n_cpus ÷ n_gpus_per_node) : 1

    # --- Script body ---
    # Everything after this line lands in the generated .sh verbatim. Bash
    # variables that we want expanded at script-run time are written as `\$X`;
    # ones expanded at generation time use the Julia `$(...)` interpolation.
    header = [
        "#!/bin/bash",
        "# Auto-generated by local_runs.jl at $(timestamp).",
        "# Codename: $(codename)",
        "# Mode:     $(mode)",
        "set -eu",
        "set -o pipefail",
        "",
        "START_TIME_SEC=\$(date +%s)",
        "echo \"=========================================\"",
        "echo \"Job started at: \$(date)\"",
        "echo \"Mode: $(mode)\"",
        "echo \"=========================================\"",
        "",
    ]

    gpu_detect = if is_test_mode
        [
            "# --- Runtime GPU detection ---",
            "# Metal on Apple Silicon, CUDA on Linux + nvidia-smi, else CPU.",
            "GPU_BACKEND=\"\"",
            "USE_GPU=\"0\"",
            "N_GPUS=0",
            "if [[ \"\$(uname -s)\" == \"Darwin\" && \"\$(uname -m)\" == \"arm64\" ]]; then",
            "    USE_GPU=\"1\"",
            "    GPU_BACKEND=\"metal\"",
            "    N_GPUS=1",
            "    echo \"[gpu] detected Apple Silicon; USE_GPU=1 GPU_BACKEND=metal\"",
            "elif command -v nvidia-smi >/dev/null 2>&1 && nvidia-smi -L >/dev/null 2>&1; then",
            "    USE_GPU=\"1\"",
            "    GPU_BACKEND=\"cuda\"",
            "    N_GPUS=\$(nvidia-smi -L | wc -l | tr -d ' ')",
            "    echo \"[gpu] detected \$N_GPUS NVIDIA GPU(s); USE_GPU=1 GPU_BACKEND=cuda\"",
            "else",
            "    echo \"[gpu] no GPU detected — falling back to CPU (USE_GPU=0)\"",
            "fi",
            "export USE_GPU",
            "export GPU_BACKEND",
            "",
            "# Concurrency: bounded by the smaller of requested-jobs and available GPUs.",
            "# Requested cap = n_gpus_per_node from the generator = $(n_gpus_per_node).",
            "if [ \"\$USE_GPU\" = \"1\" ]; then",
            "    JOBS=\$(( N_GPUS < $(n_gpus_per_node) ? N_GPUS : $(n_gpus_per_node) ))",
            "else",
            "    JOBS=$(n_cpus)",
            "fi",
            "echo \"[gpu] JOBS=\$JOBS  (threads/job: $(threads_per_job))\"",
            "",
        ]
    else
        [
            "# --- Train mode is CPU-only ---",
            "export USE_GPU=0",
            "export GPU_BACKEND=",
            "JOBS=$(n_cpus)",
            "",
        ]
    end

    thread_env = [
        "# Pin BLAS / OpenMP / Julia threads per Julia process so GNU parallel",
        "# doesn't oversubscribe cores. Use 1 in train mode (many parallel Julia",
        "# procs, each single-threaded); split cores across GPU procs in test mode.",
        "export JULIA_NUM_THREADS=$(threads_per_job)",
        "export OMP_NUM_THREADS=$(threads_per_job)",
        "export OPENBLAS_NUM_THREADS=$(threads_per_job)",
        "export MKL_NUM_THREADS=$(threads_per_job)",
        "export BLAS_NUM_THREADS=$(threads_per_job)",
        "",
    ]

    # Execution block. Branch at RUN time (not generation time) so the same
    # script works both when JOBS collapses to 1 (Apple Silicon Metal, or any
    # single-GPU / single-core machine) and when JOBS > 1 (multi-GPU Linux box).
    #
    # JOBS == 1  → sequential via bash. Skips GNU parallel entirely (no
    #              --results bookkeeping, no launch overhead), and flips
    #              `--quiet true` → `--quiet false` in each command line so
    #              Julia's progress bar prints live to the terminal instead
    #              of getting hidden in a parallel results file.
    # JOBS  > 1  → GNU parallel. In test mode + CUDA we set CUDA_VISIBLE_DEVICES
    #              per slot (single quotes defer \$((...)) evaluation until
    #              parallel substitutes {%}). In Metal there's only one device,
    #              so no per-slot binding is needed.
    seq_block = [
        "    # Sequential path — one command at a time, live stdout, --quiet=false.",
        "    total=\$(wc -l < $(commands_file) | tr -d ' ')",
        "    line_num=0",
        "    while IFS= read -r cmd; do",
        "        line_num=\$((line_num + 1))",
        "        # Enable progress output for the one command we're about to run.",
        "        cmd_verbose=\"\${cmd/--quiet true/--quiet false}\"",
        "        echo \"\"",
        "        echo \"=============== [\$line_num/\$total] ===============\"",
        "        echo \"\$ \$cmd_verbose\"",
        "        echo \"====================================================\"",
        "        eval \"\$cmd_verbose\"",
        "    done < $(commands_file)",
    ]
    parallel_test_cuda = [
        "    # `bash -c {}` is required: parallel shell-quotes {} before substitution,",
        "    # so without bash -c the shell tries to exec the whole julia command as a",
        "    # single filename and errors with \"No such file or directory\". bash -c",
        "    # re-parses the quoted string as a shell command line.",
        "    parallel --bar --jobs \$JOBS --results $(logs_dir) 'CUDA_VISIBLE_DEVICES=\$(({%} - 1)) bash -c {}' :::: $(commands_file)",
    ]
    parallel_generic = [
        "    parallel --bar --jobs \$JOBS --results $(logs_dir) < $(commands_file)",
    ]

    exec_block = vcat(
        ["if [ \"\$JOBS\" -eq 1 ]; then"],
        seq_block,
        (is_test_mode ?
            vcat(["elif [ \"\$GPU_BACKEND\" = \"cuda\" ]; then"], parallel_test_cuda) :
            String[]),
        ["else"],
        parallel_generic,
        ["fi"],
    )

    logs_dir_line = "mkdir -p $(logs_dir)  # ensure logs dir exists"
    body = vcat(
        [
            logs_dir_line,
            "",
            "if [ \"\$JOBS\" -eq 1 ]; then",
            "    echo \"[run] JOBS=1 — running commands sequentially in bash (--quiet false).\"",
            "else",
            "    echo \"[run] JOBS=\$JOBS — launching GNU parallel workers.\"",
            "fi",
        ],
        exec_block,
        [""],
    )

    footer = [
        "END_TIME_SEC=\$(date +%s)",
        "DURATION_SEC=\$((END_TIME_SEC - START_TIME_SEC))",
        "HOURS=\$((DURATION_SEC / 3600))",
        "MINUTES=\$(((DURATION_SEC % 3600) / 60))",
        "SECONDS=\$((DURATION_SEC % 60))",
        "echo \"\"",
        "echo \"=========================================\"",
        "echo \"Job finished at: \$(date)\"",
        "echo \"Total job execution time: \${HOURS}h \${MINUTES}m \${SECONDS}s\"",
        "echo \"=========================================\"",
    ]

    open(script_file, "w") do io
        println(io, join(vcat(header, gpu_detect, thread_env, body, footer), "\n"))
    end

    # Emit the same "job details" block SLURM does, so the two backends are
    # informationally symmetric from a user's perspective.
    println("\n=== Local Job Details ===")
    println("  Mode             : $(mode)")
    println("  Target codename  : $codename")
    println("  Total commands   : $n_commands")
    println("  CPUs (max jobs)  : $n_cpus")
    if is_test_mode
        println("  GPUs (max jobs)  : $n_gpus_per_node (runtime-capped by detected count)")
        println("  Threads per job  : $threads_per_job")
    end
    println("\n=== Output Files ===")
    println("  Commands file    : $commands_file")
    println("  Local script     : $script_file")
    println("  Parallel logs    : $logs_dir")
    println("\n=== To run ===")
    println("  bash $script_file\n")

    return script_file
end