using Dates
using Printf
using LinearAlgebra

function generate_parallel_commands(
    pvals::AbstractVector{<:Real},
    qvals::AbstractVector{<:Real},
    n_samples::Int;
    codename::String="aps",
    n_hidden_layers::Int=100,
    n_epochs::Int=10,
    batch_size::Int=2,
    retrain::Bool=false,
    julia_project::String="./../",
    commands_file::String="commands.txt",
    results_file::String="simulation_results.json",
    ncpus::Int=10
)
    """
    Generate shell commands for parallel execution of neural BP experiments.
    """

    open(commands_file, "w") do io
        for p in pvals, q in qvals, s in 1:n_samples

            p_str = @sprintf("%.3g", p)
            q_str = @sprintf("%.3g", q)
            samples_str = @sprintf("%d", s)

            cer_file = "correlated_weights_p_$(p_str)_q_$(q_str)_s_$(samples_str).txt"
            train_file = "train_ballistic_p_$(p_str)_q_$(q_str)_s_$(samples_str).txt"
            test_file = "test_ballistic_p_$(p_str)_q_$(q_str)_s_$(samples_str).txt"

            cmd = """julia --project="$(julia_project)" neural_bp_experiments.jl \
                --codename $(codename) \
                --n_hidden_layers $(n_hidden_layers) \
                --n_epochs $(n_epochs) \
                --batch_size $(batch_size) \
                --correlation_strengths_file $(cer_file) \
                --train $(train_file) \
                --test $(test_file) \
                --retrain $(retrain)"""

            cmd = replace(cmd, "\n" => " ")

            println(io, cmd)
        end
    end

    println("$(length(pvals) * length(qvals) * n_samples) commands written to: $commands_file\n")

    # Write a shell script to run the commands in `commands_file` in parallel, save results to `results_file`, and halt the Google Cloud VM when done.
    # The shell script should be named `run_<timestamp>.sh` and should be saved in the same directory as `commands_file`.
    timestamp = Dates.format(Dates.now(), "yyyy-mm-dd_HH-MM-SS")
    shell_script_file = joinpath(dirname(commands_file), "run_$(timestamp).sh")
    job_cmd = """parallel --bar --keep-order --jobs $ncpus --results $(results_file) --arg-file $(commands_file)"""
    open(shell_script_file, "w") do io
        wrapped_cmd = shut_down_vm(job_cmd)
        println(io, wrapped_cmd)
    end
    println("Run simulations with:")
    println("bash $(shell_script_file)\n")
end

function shut_down_vm(job_cmd::String)
    r"""
    Shutdown the Google Cloud VM after all simulations are done.
    We want to generate the shell script lines that stop the VM after all simulations are done.
    We will add these lines to wrap the shell script generated by `generate_parallel_commands`.
    """
    wrapped_cmd = [
        "#!/bin/bash",
        "set -e",
        "",
        "# Run the commands in parallel and save results to a file",
        job_cmd,
        "",
        "# Fetch the instance name and zone from the metadata server",
        r"INSTANCE_NAME=$(curl -s -H \"Metadata-Flavor: Google\" http://metadata.google.internal/computeMetadata/v1/instance/name)",
        r"ZONE=$(curl -s -H \"Metadata-Flavor: Google\" http://metadata.google.internal/computeMetadata/v1/instance/zone | awk -F/ '{print $NF}')",
        "",
        "# Stop the instance",
        r"gcloud compute instances stop $INSTANCE_NAME --zone=$ZONE"
    ]

    return join(wrapped_cmd, "\n")
end

function main()
    """
    Data set for plots in APS: aps_7q_Hamm_code_data
    p: 0.001:0.001:0.005
    q: 0.3:0.04:0.66
    """
    dirname = "7q_Hamm_code_data_10000_train"
    generate_parallel_commands(
        [0.006, 0.008],
        [0.1],
        56;
        codename = dirname,
        n_hidden_layers = 100,
        n_epochs = 20,
        batch_size = 8,
        retrain = false,
        julia_project = "./../",
        commands_file = "./../data/$(dirname)/commands.txt",
        results_file = "./../data/$(dirname)/simulation_results.json",
        ncpus = 56
    )
end